### ISSUE TITLE
This example is deprecated

### ISSUE THREAD

**Issue by KingGamma** [Bareflank/extended_apis_example_hook#11]
On Jan 16 Bareflank's master repository was merged with the EAPIs one.
Since that, the mentioned instructions (README) and a few parts of the code leads to failure.

**Comment by rianquinn** [comment]
Yes, please use RC2.0.4 if you wish to use the examples. We are in the process of merging them into the main repo as well. Once that is done, all of the repos will be deprecated in favor of the new layout.
