### ISSUE TITLE
[Question] Get exit qualification

### ISSUE THREAD

**Issue by Randshot** [Bareflank/extended_apis_example_hook#3]
Hey,

I am trying to extend this example by reading the exit qualification.
So, how do I get them? After looking at the documentation, I 'think' I found it:
```c++
intel_x64::vmcs::exit_qualification::ept_violation::data_read.is_enabled();
```
But the `ept_violation` namespace doesn't seem to have `data_execute` namespace member.
Since I only need to switch the page when the code is getting executed, I really need to know whether it is accessed that way.

After getting this to work, I plan on using shadow pages, instead of just changing the RIP.

**Comment by rianquinn** [comment]
It's called 'instruction_fetch' as that is what it's called in the Intel SDM. So the code would be:

```
intel_x64::vmcs::exit_qualification::ept_violation::instruction_fetch:: is_enabled()
```

**Comment by Randshot** [comment]
Ah, didn't know that 😄 
Anyway, thanks.

**Comment by rianquinn** [comment]
no problem, glad I could help
