### ISSUE TITLE
[Question] Trap only active on one vpcu?

### ISSUE THREAD

**Issue by Randshot** [Bareflank/extended_apis_example_hook#4]
So, I have noticed that in the user mode application, you set a process affinity mask, which if I understood it correctly, limits the application to just one CPU?

When I commented it out, and executed the app again, the trap didn't work all the time, since I assume that the trap is only active on one CPU.

Now I want to make the trap work on all CPUs.
We setup two global EPTs:
```c++
std::unique_ptr<root_ept_intel_x64> g_root_ept;
std::unique_ptr<root_ept_intel_x64> g_root_ept_hook;
```
And our EPT gets assigned to all VCPUs:
```c++
this->set_eptp(g_root_ept->eptp());
```

I think that it should then work for all VCPUs, but apparently it doesn't.
Did I miss something? And if I did, what do I have to do to make it work for all VCPUs?

**Comment by rianquinn** [comment]
each VCPU has it's own independent state, so when we call from the user space application to tell the hypervisor to hook, we are only hooking the one VCPU. If you want to apply the hook to all of the VCPUs (which is really the better approach), you need to hook all of the VCPUs by looping through each physical CPU and calling into the hypervisor to apply the hook.
