### ISSUE TITLE
error: ‘g_rsdp’ declared as an ‘inline’ variable

### ISSUE THREAD

**Issue by yshalabi** [Bareflank/extended_apis_example_hook#9]
In file included from /home/dev/bareflank/extended_apis_example_hook/userspace/hook.cpp:22:0:
/home/dev/bareflank/hypervisor/bfintrinsics/include/intrinsics.h:25:18: error: ‘g_rsdp’ declared as an ‘inline’ variable
 inline uintptr_t g_rsdp = 0;
                  ^
In file included from /home/yshalab2/bareflank/extended_apis/bfack/ack.cpp:20:0:
/home/dev/bareflank/hypervisor/bfintrinsics/include/intrinsics.h:25:18: error: ‘g_rsdp’ declared as an ‘inline’ variable
 inline uintptr_t g_rsdp = 0;
                  ^

A bit odd. Compiler error? I can work around it by simply changing the inline keyword to static, but not sure why inline isnt working considering this is a c++17 project.

**Comment by rianquinn** [comment]
what compiler are you using?

**Comment by rianquinn** [comment]
Going to close this for now. I suspect that you are not using a C++17 compiler.
